language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: GNXYexRC6v1e6c2BI7sv+AU2mdm9B2i4YTlL4lAoYXlwfPEI6+BHUXIs9lEhRsvQV2hLD2LC3T5YDBt7bS2DUBowpflswbXyod6qS8EADd11GhzVun1mZPbjt2JDOSiKp9l0sDdoS1Yg5d9l2TjiBr1iJadePdPuUTKuEVwPZ6JNVMNI8pfIKFm5d7Gpyi40IBg4r8M08sannmsV+IoYkrsz+ay2QMpeHaN2UF64TgckAcaMABjdRxbdwVnqz5M4hnYslLYcOGY567Q9Hq9VzO9ijksAsCMfZl+RetdMg6neCFl+wx9W3SHKDdn80vPMg6T2/GfkPp020XEpyx3iQhgyo9ryrmNrFX1GHnfcM5Y1wO0RwLRdriuVO5zz3I9UMbrsyTKww6Nl4TJoxnSOBOT8MURKsXUqiH/uKoOj3eaPV2/w0JVmJ6QVRbAdzf9QaDU2thd3Vt2hfFPPhg3Mrq7chTWwZRrjxvheGVQGEsW+jrLNSOBFLw7b6NladxBBA+f8McZ8N1kFTSIwjNrYi90pslxSQBKZy2cA0c8RbNuoR6WMCu3RvrhJHJvkR7KWcWffetMcfnaODBFmVHBbkoB1otU+LPH0kZVu/sLMYCiullvYLxkBWyLg+OBgUI44S+nU+mCF/z7+dbvY0o7S1IXEvRHEzCjekNq9Iyvv/ZE=
