language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: lV7yiG+hvX2ZRPJg7ZeXaEglFLqbHzuEtvr8dNXlWMVHESSei/K3DA8qIQF2f5BRJ8MPN4JHVRiTV5MDZRu1MD7qQoQHGTENxm+ryHuAm/Y1kFzVwr4DU2Jbd+H/9XHrYFCd0kkf3rW4VEaWQLINq6khGA7WqYn01PuEpB8rZk+i3wGQd/TP8QfMJu9t3g1NZzlnxfo+/YKQ9SxX5UVgbdrIDuFv30xv6fO6geSW6KkV2K+itbGTo+mEYN9CAVvYS5ROy5bjyjLIXYxMccvgppKwpny6purnFcQbCiHalJ9ven3soxS5Z6p8OifK/F+XP3/Hel1y42vswTTtYiDMwsa22LADFx5Icnqk+nxbt+Bj48skYhQnMC0b1Syqup9lOSkLzxQAV63kW63J1Rh03LJPUFMYUa9EapLOKOW/GPA4nabIki4SYT7DaMQmce/4ojppmqQnTTC/zG62thRsDClZeSn4lFxAFRlwiuu/Qh5I9kSc4o/DPOF/bVrkJjycm0iJtOVeD9O2LEtiKMOQlBqOTBoArHPL32XOXa9jv1hJxVbwb7ZUHT96sS5NKlQII/bIpvDiVaEHqx7+xiWqkh+F8sEONtWjS3oQ/5XpHFlhJZAqCT9nakfuEA7mkeg6HyeLXsTXCkQbhkla4gH+m5qQJsoAs9cbJgnokVAWaaU=
